data:
  name: 'MRIDataset'
  dir: '/media/haohanwang/Info/ADNI_CAPS'
  params:
    weighted_sampler: True
    idx_fold: 0
    num_fold: 5

model:
  name: 'Conv5_FC3'
  params:
    dropout: 0.5
    dropblock: False
    blocksize: 10
    convKernel1: 3
    poolKernel1: 2
    convKernel2: 3
    poolKernel2: 2
    poolKernel3: 2
    fcSize1: 32256
    fcSize2: 1300

train:
  dir: ../results/checkpoints/policy2_1e-4_dr_0.5_eps_5e-3_dropblock/
  batch_size: 8
  num_epochs: 25

optimizer:
  name: 'adam'
  params:
    lr: 0.0001

pgd:
  use: False
  eps: 0.005
  alpha: 0.000125
  iters: 10
  loss:
    alpha: 0.01

transform:
  name: 'MinMaxNormalization'
  num_preprocessor: 4
