data:
  name: 'MRIDataset'
  dir: 'ADNI_CAPS'
  params:
    weighted_sampler: True
    idx_fold: 0
    num_fold: 5

model:
  name: 'Conv5_FC3'
  params:
    dropout: 0.2945
    dropblock: False
    blocksize: 10

train:
  dir: ./searchResults/
  batch_size: 6
  num_epochs: 25

optimizer:
  name: 'adam'
  params:
    lr: 0.000247

pgd:
  use: False
  eps: 0.005
  alpha: 0.000125
  iters: 10
  loss:
    alpha: 0.01

transform:
  name: 'MinMaxNormalization'
  num_preprocessor: 4
