data:
  name: 'MRIDataset'
  dir: 'ADNI_CAPS'
  params:
    idx_fold: 0
    num_fold: 5

model:
  name: 'Conv5_FC3'

train:
  dir: './results/policy_eps5e-3_lr1e-5_weight_dropblock'
  batch_size: 4
  num_epochs: 25

optimizer:
  name: 'adam'
  params:
    lr: 0.00001

pgd:
  eps: 0.005
  alpha: 0.000125
  iters: 10

transform:
  name: 'MinMaxNormalization'
  num_preprocessor: 4
